### ISSUE TITLE
Add http://blog.grafixartist.com

### ISSUE THREAD

**Issue by Suleiman19** [ziem/android-development-blogs#23]
**Title:** Grafix Artist Blog
**Website URL:** http://blog.grafixartist.com
**Feed URL:** http://blog.grafixartist.com/feed/
**Description:** Android Design & Dev Blog

**Comment by Suleiman56060** [comment]
_Updated blog link. @ziem _
Title: Grafix Artist Blog
**Website URL:** http://blog.iamsuleiman.com
**Feed URL:** http://blog.iamsuleiman.com/feed/

**Comment by ziem** [comment]
Done.
