### ISSUE TITLE
List of excerpts-only feeds

### ISSUE THREAD

**Issue by MorganRamsay** [ziem/android-development-blogs#40]
A number of sites in the OPML don't exist anymore, or haven't been updated in years. I didn't keep track of the feeds to which I didn't subscribe. But here are the feeds that don't offer full text:

- `angrybyte.me`
- `chris.banes.me`
- `crushingcode.nisrulz.com`
- `blog.iamsuleiman.com`
- `hannesdorfmann.com`
- `jeroenmols.com`
- `blahti.wordpress.com`
- `medium.com/@patrykpoborca`
- `riggaroo.co.za`
- `therealjoshua.com`
- `wiresareobsolete.com`
- `zserge.com`

I don't know if you want to add this information to the table.

**Comment by ziem** [comment]
Thanks for your comment 👍 .

I did some maintenance and removed/updated some feeds:
❌ http://alexsimo.com/
❌ http://androiddesignpatterns.blogspot.com/
❌ http://arjunu.com
❌ http://blog.callumtaylor.net/
❌ http://jorgecastilloprz.github.io/
❌ http://www.marcouberti.net/
❌ http://matthewwear.xyz/
❌ http://www.mounacheikhna.com/
❌ http://nerds.weddingpartyapp.com/
http://frogermcs.github.io ➡️ https://mirekstanek.online/
Gadget Habit ➡️ Michael Evans

I think I will keep everything as it is now, but leave this issue open to let readers know.
